// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1hlZ2rILU6aJHzpLR_3FakGHKHfrHqA',
    appId: '1:206980086854:web:f578626aa40c761ead1e47',
    messagingSenderId: '206980086854',
    projectId: 'chatapp-d117f',
    authDomain: 'chatapp-d117f.firebaseapp.com',
    storageBucket: 'chatapp-d117f.appspot.com',
    measurementId: 'G-TWET3G8DWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0by7AgV4gXXo3fQArvZyqaTDJeZmu91w',
    appId: '1:206980086854:android:22ff556ea836f11cad1e47',
    messagingSenderId: '206980086854',
    projectId: 'chatapp-d117f',
    storageBucket: 'chatapp-d117f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASV5WrmWzf9ycGhFeW4j_ub7cuT0VhWrI',
    appId: '1:206980086854:ios:d7d8586e8dbed269ad1e47',
    messagingSenderId: '206980086854',
    projectId: 'chatapp-d117f',
    storageBucket: 'chatapp-d117f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASV5WrmWzf9ycGhFeW4j_ub7cuT0VhWrI',
    appId: '1:206980086854:ios:d7d8586e8dbed269ad1e47',
    messagingSenderId: '206980086854',
    projectId: 'chatapp-d117f',
    storageBucket: 'chatapp-d117f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq1hlZ2rILU6aJHzpLR_3FakGHKHfrHqA',
    appId: '1:206980086854:web:9e4cb6cd9203d2f7ad1e47',
    messagingSenderId: '206980086854',
    projectId: 'chatapp-d117f',
    authDomain: 'chatapp-d117f.firebaseapp.com',
    storageBucket: 'chatapp-d117f.appspot.com',
    measurementId: 'G-KLLDQCH4NS',
  );

}